# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: debug-statements
  - id: detect-private-key
  - id: check-toml
  - id: check-case-conflict
  - id: check-added-large-files
    args: [--maxkb=1000]
  - id: check-json
  - id: check-merge-conflict
  - id: check-shebang-scripts-are-executable
  - id: fix-byte-order-marker
  - id: fix-encoding-pragma
    args: [--remove]
  - id: mixed-line-ending
    args: [--fix=lf]
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.10.0.1
  hooks:
  - id: shellcheck
- repo: https://github.com/kynan/nbstripout
  rev: 0.7.1
  hooks:
    - id: nbstripout
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.0
  hooks:
  - id: ruff
    args: [--fix]
  - id: ruff-format
- repo: https://github.com/RobertCraigie/pyright-python
  rev: v1.1.370
  hooks:
  - id: pyright
- repo: https://github.com/astral-sh/uv-pre-commit
  # uv version.
  rev: 0.2.13
  hooks:
    - id: pip-compile
      name: pip-compile pyproject.toml
      args: [pyproject.toml, -o, requirements.lock]
      files: pyproject.toml
    - id: pip-compile
      name: pip-compile requirements-dev.in
      args: [requirements-dev.in, -o, requirements-dev.lock]
      files: requirements-dev.in
