[project]
name = "ted"
version = "0.1.0"
description = "Topology-based Estimation of Distribution algorithm"
authors = [
    { name = "Francesco Gentile", email = "francesco.gentile@studenti.unitn.it" },
    { name = "Manuela Corte Pause", email = "manuela.cortepause@studenti.unit.it" },
]
dependencies = [
    "numpy>=1.24",
    "torch>=2.0",
    "entmax>=1.3",
    "hydra-core>=1.3",
]
readme = "README.md"
license.file = "LICENSE"
requires-python = ">= 3.10"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "pre-commit>=3.7",
    "ruff>=0.4",
    "pyright>=1.1.361",
    "ipykernel>=6.29",
    "matplotlib>=3.8",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/ted"]
