fix = true
line-length = 88
src = ["src"]
target-version = "py310"

[format]
preview = true

[lint]
fixable = ["ALL"]
ignore = [
    "ANN101",
    "ANN401",
    "COM812",
    "ERA001",
    "ISC001",
    "PGH003",
    "RET504",
]
select = ["ALL"]

[lint.pydocstyle]
convention = "google"
