# Copyright 2024 TED Team.
# SPDX-License-Identifier: Apache-2.0

seed: 42

model:
  num_nodes: 10

optimizer:
  _target_: torch.optim.AdamW
  lr: 0.001
  weight_decay: 0.01

problem:
  _target_: ted.problems.SphereFunction

loggers:
- _target_: ted.loggers.FileLogger
  log_every_n_steps: 10
- _target_: ted.loggers.WandbLogger
  project: "ted"
  log_every_n_steps: 10
- _target_: ted.loggers.ProgressBarLogger

engine:
  genome_size: 10
  batch_size: 64
  buffer_size: 1000
  sampling_old_ratio: 0.8
  sampling_steps: 50
  sampling_noise_std: 0.01
  sampling_step_size: 0.01
  gradient_clip_norm: 1.0
  max_evaluations: 12800
  device: "cuda:0"
